version: "3"

services:
  ai:
    container_name: fingaroo
    image: fingaroo
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
